<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
	<xacro:include filename="inertia.urdf.xacro" />
	<xacro:include filename="materials.urdf.xacro" />

	<link name="world"></link>

	<xacro:property name="height" value="1.2" />
	<joint name="base_joint" type="fixed">
		<origin xyz="0 0 1.2" rpy="0 0 0" />
		<parent link="world" />
		<child link="base_link" />
	</joint>

	<xacro:property name="base_w" value="1.5" />
	<xacro:property name="base_l" value="1.5" />
	<xacro:property name="base_h" value="0.1" />
	<xacro:property name="base_m" value="5" />
	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<geometry>
				<box size="${base_w} ${base_l} ${base_h}" />
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<geometry>
				<box size="${base_w} ${base_l} ${base_h}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 ${base_h/2}" rpy="0 0 0" />
			<mass value="${base_m}" />
			<xacro:box_inertia m="${base_m}" x="${base_w}" y="${base_l}" z="${base_h}" />
		</inertial>
	</link>

	<joint name="first_axis_joint" type="prismatic">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="base_link" />
		<child link="first_axis_link" />
		<axis xyz="0 1 0" />
		<limit lower="${-base_l/2}" upper="${base_l/2}" velocity="100" effort="100" />
	</joint>

	<xacro:property name="first_w" value="0.2" />
	<xacro:property name="first_l" value="0.2" />
	<xacro:property name="first_h" value="0.2" />
	<xacro:property name="first_m" value="0.5" />
	<link name="first_axis_link">
		<visual>
			<origin xyz="0 0 ${-first_h/2}" rpy="0 0 0" />
			<geometry>
				<box size="${first_w} ${first_l} ${first_h}" />
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${-first_h}" rpy="0 0 0" />
			<geometry>
				<box size="${first_w} ${first_l} ${first_h}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 ${-first_h/2}" rpy="0 0 0" />
			<mass value="${first_m}" />
			<xacro:box_inertia m="${first_m}" x="${first_w}" y="${first_l}" z="${first_h}" />
		</inertial>
	</link>

	<joint name="second_axis_joint" type="revolute">
		<origin xyz="0 0 ${-first_h}" rpy="0 0 0" />
		<parent link="first_axis_link" />
		<child link="second_axis_link" />
		<axis xyz="0 1 0" />
		<limit lower="${-pi/2}" upper="${pi/2}" velocity="100" effort="100" />
	</joint>

	<xacro:property name="arm_length" value="0.6" />
	<xacro:property name="arm_radius" value="0.05" />
	<xacro:property name="arm_mass" value="1" />
	<link name="second_axis_link">
		<visual>
			<origin xyz="0 0 ${-arm_length/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}" />
			</geometry>
			<material name="orange"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${-arm_length/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 ${-arm_length/2}" rpy="0 0 0" />
			<mass value="${arm_mass}" />
			<xacro:cylinder_inertia m="${arm_mass}" r="${arm_radius}" h="${arm_length}" />
		</inertial>
	</link>


	<xacro:property name="arm2_radius" value="0.05" />
	<xacro:property name="arm2_length" value="0.6" />
	<xacro:property name="arm2_mass" value="0.5" />
	<joint name="third_axis_joint" type="continuous">
		<origin xyz="0 0 ${-arm_length}" rpy="0 0 0" />
		<parent link="second_axis_link" />
		<child link="third_axis_link" />
		<axis xyz="0 1 0" />
	</joint>

	<link name="third_axis_link">
		<visual>
			<origin xyz="0 0 ${-arm2_length/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm2_length}" radius="${arm2_radius}" />
			</geometry>
			<material name="orange"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${-arm2_length/2}" rpy="0 0 0" />
			<geometry>
				<cylinder length="${arm2_length}" radius="${arm2_radius}" />
			</geometry>
		</collision>
		<inertial>
			<origin xyz="0 0 ${-arm2_length/2}" rpy="0 0 0" />
			<mass value="${arm2_mass}" />
			<xacro:cylinder_inertia m="${arm2_mass}" r="${arm2_radius}" h="${arm2_length}" />
		</inertial>
	</link>

	<xacro:property name="top_w" value="0.2" />
	<xacro:property name="top_l" value="0.2" />
	<xacro:property name="wheel_r" value="0.2" />
	<xacro:property name="wheel_l" value="0.1" />
	<xacro:property name="wheel_m" value="5" />
	<xacro:property name="top_h" value="${height-2*wheel_r}" />
	<xacro:macro name="wheel" params="prefix x y">
		<joint name="${prefix}_wheel_joint" type="fixed">
			<parent link="base_link" />
			<child link="${prefix}_wheel_link" />
			<origin xyz="${x} ${y} 0" rpy="0 0 0" />
		</joint>

		<link name="${prefix}_wheel_link">
			<visual>
				<origin xyz="0 0 ${-top_h/2}" rpy="0 0 0"/>
				<geometry>
					<box size="${top_w} ${top_l} ${top_h}" />
				</geometry>
				<material name="blue"/>
			</visual>
			<visual>
				<origin xyz="0 0 ${-top_h-wheel_r}" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${wheel_r}" length="${wheel_l}" />
				</geometry>
				<material name="blue"/>
			</visual>
			<collision>
				<origin xyz="0 0 ${-top_h/2-wheel_r}" rpy="0 0 0"/>
				<geometry>
					<box size="${top_w} ${2*wheel_r} ${top_h+2*wheel_r}" />
				</geometry>
			</collision>
			<inertial>
				<origin xyz="0 0 ${-top_h/2-wheel_r}" rpy="0 0 0"/>
				<mass value="${wheel_m}" />
				<xacro:box_inertia m="${wheel_m}" x="${top_w}" y="${2*wheel_r}" z="${top_h+2*wheel_r}" />
			</inertial>
		</link>
	</xacro:macro>

	<xacro:wheel prefix="fl" x="${-base_w/2+top_w/2}" y="${base_l/2-top_l/2}" />
	<xacro:wheel prefix="bl" x="${-base_w/2+top_w/2}" y="${-base_l/2+top_l/2}" />
	<xacro:wheel prefix="fr" x="${base_w/2-top_w/2}" y="${base_l/2-top_l/2}" />
	<xacro:wheel prefix="br" x="${base_w/2-top_w/2}" y="${-base_l/2+top_l/2}" />
</robot>
